server:
  port: 8085
  
spring:
  rabbitmq:
    port: 5672
    host: ec2-3-128-80-159.us-east-2.compute.amazonaws.com
    username: guest2 
    password: "PvVf2pk&X9Xm%3"
  
  datasource:
    url: jdbc:postgresql://${REVATURE_POSTGRES_URL}:5432/${REVATURE_POSTGRES_DB}?
    username: ${REVATURE_POSTGRES_USERNAME}
    password: ${REVATURE_POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver 
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        format-sql: true

  main:
    banner-mode: off
  mail:
    protocol: smtp
    host: smtp.mailtrap.io
    port: 2525
    username: 2630cc7e4b74ae
    password: b464df1bb71bb2
    properties:
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true  
        
     
        
        
