
server:
  port: 8085
  
spring:
  rabbitmq:
    port: 5672
    host: ec2-3-128-80-159.us-east-2.compute.amazonaws.com
    username: guest2 
    password: "PvVf2pk&X9Xm%3"
    
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    
    
    hibernate:
      ddl-auto: create-drop
  
      
  datasource:
    platform: postgres
    url: jdbc:postgresql://revature-db.cj2nb1xoq6zr.us-east-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: "admin#123"
    driverClassName: org.postgresql.Driver